name: "CI"
on:
  pull_request:
    branches:
      - main

jobs:
  # unit tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  windows-sample-job:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: uipath-setup
        uses: ./
      - run: uipcli package analyze ${{ github.workspace }}/SampleUiPathProject/project.json

  commitsar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitsar Action
        uses: aevea/commitsar@v0.20.2