# Basic workflow for utilizing GitHub Actions for CI on UiPath projects
name: UiPath CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  
  windows-setup:
    # The type of runner that the job will run on
    runs-on: windows-2019
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: uipath-setup
        uses: ./
      - run: uipcli package analyze ${{ github.workspace }}/SampleUiPathProjectNewWindows/BlankProcess/project.json --orchestratorUrl https://cloud.uipath.com/ --orchestratorTenant ${{ secrets.UIPATH_TENANT }} --orchestratorAccountForApp ${{ secrets.UIPATH_ORGANIZATION_ID }} --orchestratorApplicationId "${{ secrets.UIPATH_APP_ID }}" --orchestratorApplicationSecret "${{ secrets.UIPATH_APP_SECRET }}" --orchestratorApplicationScope "${{ secrets.UIPATH_APP_SCOPE }}" --orchestratorFolder "Shared"
  
  #ubuntu-setup:
    # The type of runner that the job will run on
  #  runs-on: ubuntu-latest
  #  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #    - uses: actions/checkout@v3
  #    - name: UiPath-Setup-JS
  #      uses: ./
  #    - run: uipcli package analyze ${{ github.workspace }}/SampleUiPathProject/project.json
