# Basic workflow for utilizing GitHub Actions for CI on UiPath projects
name: UiPath CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  windows-setup:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup-uipath
        uses: ./
      - run: uipcli package analyze ${{ github.workspace }}/SampleUiPathProject/project.json
  
  ubuntu-setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup-uipath
        uses: ./
      - run: dotnet uipcli.dll package analyze ${{ github.workspace }}/SampleUiPathProject/project.json
